### ISSUE TITLE
Link to slides in Readme is incorrect

### ISSUE THREAD

**Issue by emanuelhuber** [marionlouveaux/rr2021_bookprep#1]
Hello Mario
Thank you for sharing your slides.
The link to the slides in the readme file is incorrect. Should it be: https://marionlouveaux.github.io/rr2021_bookprep?
Best,

Emanuel

**Comment by marionlouveaux** [comment]
Hi Emmanuel,
Thank you for spotting this!!
I corrected the link in the README.
Best,

Marion
